export function loadGallery(mainElement) {
    const imageList = [
    "images/galerija/gallery-image-1.jpeg",
    "images/galerija/gallery-image-2.jpeg",
    "images/galerija/gallery-image-3.jpeg",
    "images/galerija/gallery-image-4.jpeg",
    "images/galerija/gallery-image-5.jpeg",
    "images/galerija/gallery-image-6.jpeg",
    "images/galerija/gallery-image-7.jpeg",
    "images/galerija/gallery-image-8.jpeg",
    "images/galerija/gallery-image-9.jpeg",
    "images/galerija/gallery-image-10.jpeg",
    "images/galerija/gallery-image-11.jpeg",
    "images/galerija/gallery-image-12.jpeg",
    "images/galerija/gallery-image-13.jpeg",
    "images/galerija/gallery-image-14.jpeg",
    "images/galerija/gallery-image-15.jpeg",
    "images/galerija/gallery-image-16.jpeg",
    "images/galerija/gallery-image-17.jpeg",
    "images/galerija/gallery-image-18.jpeg",
    "images/galerija/gallery-image-19.jpeg",
    "images/galerija/gallery-image-20.jpeg",
    "images/galerija/gallery-image-21.jpeg",
    "images/galerija/gallery-image-22.jpeg",
    "images/galerija/gallery-image-23.jpeg",
    "images/galerija/gallery-image-24.jpeg",
    "images/galerija/gallery-image-25.jpeg",
    "images/galerija/gallery-image-26.jpeg",
    "images/galerija/gallery-image-27.jpeg",
    "images/galerija/gallery-image-28.jpeg",
    "images/galerija/gallery-image-29.jpeg",
    "images/galerija/gallery-image-30.jpeg",
    "images/galerija/gallery-image-31.jpeg",
    "images/galerija/gallery-image-32.jpeg",
    "images/galerija/gallery-image-33.jpeg",
    "images/galerija/gallery-image-34.jpeg",
    "images/galerija/gallery-image-35.jpeg",
    "images/galerija/gallery-image-36.jpeg",
    "images/galerija/gallery-image-37.jpeg",
    "images/galerija/gallery-image-38.jpeg",
    "images/galerija/gallery-image-39.jpeg",
    "images/galerija/gallery-image-40.jpeg",
    "images/galerija/gallery-image-41.jpeg",
    "images/galerija/gallery-image-42.jpeg",
    "images/galerija/gallery-image-43.jpeg",
    "images/galerija/gallery-image-44.jpeg",
    "images/galerija/gallery-image-45.jpeg",
    "images/galerija/gallery-image-46.jpeg",
    "images/galerija/gallery-image-47.jpeg",
    "images/galerija/gallery-image-48.jpeg",
    "images/galerija/gallery-image-49.jpeg",
    "images/galerija/gallery-image-50.jpeg",
    "images/galerija/gallery-image-51.jpeg",
    "images/galerija/gallery-image-52.jpeg",
    "images/galerija/gallery-image-53.jpeg",
    "images/galerija/gallery-image-54.jpeg",
    "images/galerija/gallery-image-55.jpeg",
    "images/galerija/gallery-image-56.jpeg",
    "images/galerija/gallery-image-57.jpeg",
    "images/galerija/gallery-image-58.jpeg",
    "images/galerija/gallery-image-59.jpeg",
    "images/galerija/gallery-image-60.jpeg",
];

    imageList.forEach(imagePath => {
        const imgElement = document.createElement('img');
        imgElement.src = imagePath;
        imgElement.alt = `Slika iz galerije: ${imagePath}`;
        imgElement.classList.add('gallery-image');
        mainElement.appendChild(imgElement);
    });
}